# <center> Homework 1 </center>

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня 

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

<img src="https://cdn-images-1.medium.com/max/1600/0*MVkCW8_Bmj-nuAnI.png" width="300">

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных. 

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией. 
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [54]:
N = int(input('Сколько сегодня хоббитов? '))
K = int(input('А сколько у нас кусков хлеба? '))
if N <= K:
    def share_bread(N, K):
        x = K // N
        y = K % N
        return x, y
    res = share_bread(N, K)
    print(f'Каждому страдальцу достанется по {res[0]}, а в корзинке - {res[1]}.')
else:
    print('Хоббиты остались голодными.')

print('******************************')
print(share_bread(N, K))
# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14) == (4, 2)

Сколько сегодня хоббитов? 3
А сколько у нас кусков хлеба? 14
Каждому страдальцу достанется по 4, а в корзинке - 2.
******************************
(4, 2)


## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [56]:
year = int(input('Какое число высечено на стене? '))
def leap_year(year):
    if (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:
        text_result = "YOU SHALL PASS"
    else:
        text_result = "YOU SHALL NOT PASS"
    return text_result
print(leap_year(year))

assert leap_year(5) == 'YOU SHALL NOT PASS'

Какое число высечено на стене? 6
YOU SHALL NOT PASS


## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>
Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

Подсказка: используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [57]:
from math import sqrt

def amulet_area(a, b, c):
        p = (a + b + c)/2
        S = int(sqrt(p * (p - a) * (p - b) * (p - c)))
        return S
    
a = int(input('Введите сторону: '))
b = int(input('Веедите ишшо сторону: '))
c = int(input('И третью: '))
if a + b > c and a + c > b and b + c > a:
    print(f'Площадь амулета Гендальфа - {amulet_area(a, b, c)}')
else:
    print('Не бывает таких амулетов, Гендальф, измеряй ещё раз.')

assert amulet_area(3, 4, 5) == 6

Введите сторону: 3
Веедите ишшо сторону: 4
И третью: 5
Площадь амулета Гендальфа - 6


## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - напистаь функцию под каждую из них. Важное условие - используйте только базовые функции numpy для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [58]:
import numpy as np

In [62]:
N = int(input('В каком пространстве обретаетесь, хоббиты? '))
dot_1 = list(map(int, input('Координаты точки пребывания: ').split()[:N]))
dot_2 = list(map(int, input('Координаты Мордора: ').split()[:N]))
a = np.array(dot_1)
b = np.array(dot_2)

def cal_euclidean(a, b):
    sum_square = np.sum(np.square(a - b))
    distance = round(np.sqrt(sum_square), 2)
    return distance

print(f'Евклидово расстояние до Мордора - {cal_euclidean(a, b)},')

def cal_manhattan(a, b):    
    distance = np.sum(abs(a - b))
    return distance

print(f'а манхэттенское - {cal_manhattan(a, b)},')

def cal_cosine(a, b): 
    norm_a = np.sqrt((np.sum(np.square(a)))) #norm_a = np.linalg.norm(a)
    norm_b = np.sqrt((np.sum(np.square(b)))) #norm_b = np.linalg.norm(b)
    scal = np.dot(a.T, b)
    scal_norm = scal/(norm_a*norm_b)
    #print(f'и косинусное сходство - {scal_norm}')
    distance = 1 - scal_norm
    return distance

print(f'Близко ли в смысле косинуса? - {cal_cosine(a, b)}.')

В каком пространстве обретаетесь, хоббиты? 3
Координаты точки пребывания: 2 3 4
Координаты Мордора: 6 9 17
Евклидово расстояние до Мордора - 14.87,
а манхэттенское - 23,
Близко ли в смысле косинуса? - 0.013898176392089345.


### Чем ближе косинус(scal_norm) к единице (большое косинусное сходство), тем меньше сил потратят хоббиты на дорогу, ибо значит, что до Мордора - рукой подать(distance).

In [63]:
a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))

28.57
76
1.1982419768998094


## Задача 5

Ну и напоследок, еще немного практики numpy, без которой не обходится ни один хоббит.


Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в итнтервале от 0 до 1 остаются прежними

In [64]:
my_array = np.random.rand(100)
my_array[my_array == np.min(my_array)] = 0
my_array[my_array == np.max(my_array)] = 1
print(np.max(my_array), np.min(my_array))
print(my_array)

1.0 0.0
[0.91770914 0.56218086 0.37146438 0.95213841 0.39143565 0.66213793
 0.851465   0.0180497  0.47099014 0.18560274 0.79177372 0.34427851
 0.06828657 0.72255722 0.87945969 0.26442158 0.66215822 0.441004
 0.54740312 0.16992459 0.72101808 0.80426532 0.10017936 0.82626644
 0.785867   0.28783959 1.         0.51337129 0.24708488 0.78888787
 0.82032722 0.54177798 0.39477233 0.30334929 0.59380883 0.84247388
 0.37087982 0.42313828 0.70474853 0.95663793 0.8604419  0.2577127
 0.60927409 0.13901405 0.54782381 0.33631173 0.27304007 0.68942606
 0.3754098  0.0179313  0.62581763 0.26744262 0.01628871 0.97243226
 0.70531673 0.68835804 0.08471051 0.21345575 0.32369497 0.72125969
 0.3758914  0.81270367 0.83129905 0.0209324  0.         0.54091297
 0.92798667 0.8271423  0.76330292 0.7783417  0.62021342 0.1978857
 0.2648782  0.54852407 0.65136343 0.98100804 0.27362247 0.07176265
 0.46205008 0.4147447  0.51022147 0.73214809 0.1972587  0.01613854
 0.04562057 0.16289409 0.78180015 0.37404583 0.85630416 0.

Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы 

In [65]:
my_array = np.random.randint(0, 51, (5, 6))
selected_column = my_array[:, np.argmax(my_array.max(axis=0))]
print('Shape: ',my_array.shape)
print('Array')
print(my_array)
a = np.max(my_array)
print(f'Максимальный элемент: {a}')
print(f'Колонка, содержащая а: {selected_column}')

Shape:  (5, 6)
Array
[[34  4 48 50 38 11]
 [29 33  0 31  1 35]
 [ 7 16  2 19 45 39]
 [24 33 38  7 38 11]
 [16 20 13 16 23 18]]
Максимальный элемент: 50
Колонка, содержащая а: [50 31 19  7 16]


Напишите функцию, которая принимает на вход матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [66]:
def get_unique_rows(X):
    X_unique = np.unique(X, axis=0)
    return X_unique

In [67]:
X = np.random.randint(4, 6, size=(10,3))
print(X)

[[5 4 4]
 [4 4 5]
 [4 5 4]
 [5 4 4]
 [5 4 5]
 [5 4 4]
 [4 5 5]
 [4 5 5]
 [4 4 4]
 [5 5 4]]


In [68]:
get_unique_rows(X)

array([[4, 4, 4],
       [4, 4, 5],
       [4, 5, 4],
       [4, 5, 5],
       [5, 4, 4],
       [5, 4, 5],
       [5, 5, 4]])